version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_todolist
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: devlil0
      POSTGRES_PASSWORD: 7020
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: